Avoid set-crate-version since it cannot handle triple-quoted strings
When trying to set the version number for a crate (my lipsum crate)
which uses triple-quoted strings, I get an error:

    Error: Mismatch between location and raw string, expected 7 lines for """"
    Lipsum is a lorem ipsum text generation library. Use this if you need
    filler or dummy text for your application.

    The text is generated using a simple Markov chain, which you can also
    instantiate to generate your own pieces of pseudo-random text.
    """"

This is now reported as thomaseizinger/set-crate-version#2, and in the
meantime, we’ll simply use Python to do the search-and-replace.